"""
Daily Email Summary — Sends performance report at midnight IST.

Contains:
  - Daily/Weekly P&L
  - Trade count and win rate
  - Average psychology score
  - Edge decay warning if applicable
"""

import logging
import smtplib
from email.mime.text import MIMEText
from journal.journal import get_account_state, get_journal_context
import config

logger = logging.getLogger(__name__)

def send_daily_summary():
    """Build and send the daily performance summary email."""
    if not getattr(config, 'EMAIL_ENABLED', False):
        logger.info("Email summary disabled (no credentials in .env)")
        return

    account = get_account_state()
    context = get_journal_context()
    
    body = f"""
    📊 AURUM DAILY PERFORMANCE SUMMARY
    Date: {config.get_ist_now().strftime('%Y-%m-%d')}
    
    --- ACCOUNT ---
    Balance: ${account['balance']:.2f}
    Daily P&L: ${account['daily_pnl']:.2f}
    Weekly P&L: ${account['weekly_pnl']:.2f}
    Trades Today: {account['trades_today']}
    
    --- EDGE STATUS ---
    Rolling Win Rate: {context.get('rolling_win_rate', 0):.1f}%
    Status: {context.get('edge_status', 'Unknown')}
    
    --- PSYCHOLOGY ---
    Avg Score: {context.get('avg_psych_score', 'N/A')}
    
    Generated by XAUUSD Analyst v4.0
    """
    
    msg = MIMEText(body)
    msg["Subject"] = f"AURUM Daily Report: {account['daily_pnl']:+.2f}"
    msg["From"] = config.SMTP_USER
    msg["To"] = config.ALERT_EMAIL
    
    try:
        with smtplib.SMTP_SSL(config.SMTP_HOST, config.SMTP_PORT) as server:
            server.login(config.SMTP_USER, config.SMTP_PASS)
            server.send_message(msg)
        logger.info("Daily email summary sent.")
    except Exception as e:
        logger.error(f"Failed to send email summary: {e}")
